apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::260040601681:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AW1R14YBQZME
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::260040601681:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-21T21:38:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1784"
  uid: f4d8f535-d353-4db0-9644-10e81ead26ed
